# auth-server のベース URL（API 呼び出し・H2 コンソールリンクなどで使用）
app:
  auth-server:
    url: http://localhost:9000

server:
  port: 8080
  # Cookie を `JSESSIONID` から `JSESSIONID-C-G2` に変更
  servlet:
    session:
      cookie:
        name: JSESSIONID-C-G2

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  application:
    name: auth-client-g2
  ssl:
    bundle:
      jks:
        gebo-client:
          key:
            alias: gebo-client-sample
            password: password
          keystore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
  security:
    oauth2:
      client:
        registration:
          gebo-client-oidc:
            provider: spring
            client-id: gebo-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: gebo-client-oidc
        provider:
          spring:
            issuer-uri: ${app.auth-server.url}
